class mapAreas {
    exclude[] = {
        "kavalaguv",
        "kavalaseftaliguv",
        "bakirislemeguv",
        "demirislemeguv",
        "bakirmadeniguv",
        "rebelguv",
        "bagisciguv",
        "havalaaniguv1",
        "havalaaniguv2",
        "pyrgosguv",
        "sofiaguv",
        "adaguv",
        "bagisciguv_2",
        "ada",
        "guvenlibolge_22",
        "havaalanimed",
        "guvenlibolge_3",
        "xoetkinlik",
        "ifestionaguv"
    };
    filters[] = {
        {
            "Legal Bahceler",
            {
                "apple_1",
                "apple_2",
                "apple_3",
                "apple_4",
                "peaches_1",
                "peaches_2",
                "peaches_3",
                "mantartarlasi",
                "tutuntarlasi"
            }
        },
        {
            "Legal Madenler",
            {
                "copper_mine",
                "iron_mine",
                "salt_mine",
                "sand_mine",
                "diamond_mine",
                "rock_quarry",
                "oil_field_1",
                "oil_field_2",
                "bormadeni"
            }
        },
        {
            "Legal Islemeler",
            {
                "copper_mine_1",
                "iron_processing",
                "salt_processing",
                "sand_processing",
                "diamond_processing",
                "rock_processing",
                "OilP",
                "borisleme",
                "mantarisleme",
                "tutunisleme",
                "odunfabrikasi",
                "baliktemiz"
            }
        },
        {
            "Legal Saticilar",
            {
                "iron_copper_trader",
                "salt_trader",
                "glass_trader",
                "diamond_trader",
                "oil_trader_3_1",
                "oil_trader",
                "borticaret",
                "fish_market_1",
                "mantarticareti",
                "tutunticareti",
                "odunticaret",
                "kordonbalikhali"
            }
        },
        {
            "Illegal Bahceler",
            {
                "turtle_1_name",
                "turtle_1_name_1",
                "turtle_1_name_2",
                "heroin_1",
                "cocaine_1",
                "weed_1",
                "jamaikatarlasi",
                "bonzaitarlasi",
                "multecikacirma",
                "mdma_ecstasy"
            }
        },
        {
            "Illegal Islemeler",
            {
                "cocaine_processing",
                "heroin_p",
                "Weed_p_1",
                "bonzaisleme",
                "ecstasy",
                "jamaikaisleme",
                "heroin_p"
            }
        },
        {
            "Illegal Saticilar",
            {
                "Dealer_1",
                "Dealer_1_3",
                "Dealer_1_4",
                "gold_bar_dealer",
                "turle_dealer",
                "multeciulastirma",
                "turle_dealer_2"
            }
        },
        {
            "Rebel Aktiviteleri",
            {
                "gang_area_1",
                "gang_area_3",
                "gang_area_5",
                "Suri_1",
                "Sofia",
                "Suri",
                "fed_reserve"
            }
        },
        {
            "Etkinlik Sorumlulari",
            {
                "etkinlikxox",
                "etkinlikxox_10",
                "etkinlikxox_100",
                "etkinlikxox_19",
                "etkinlikxox_27",
                "etkinlikxox_35",
                "etkinlikxox_43",
                "etkinlikxox_54",
                "etkinlikxox_70",
                "etkinlikxox_78",
                "etkinlikxox_9"
            }
        }
    };
};